problem_statements = [
    {
        "id": "PS-01",
        "round": "round-2",
        "domain": "student-grievance",
        "domainLabel": "Student Grievance Management",
        "title": "Student Grievance Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages student grievances, complaints, requests, escalation, and resolution across an educational institution.",
        "fullDescription": "Student grievance management involves changing information about complaints, academic issues, facilities, faculty, fees, and institutional services. The AI agent should classify grievances, identify responsible departments, prioritize them based on urgency and severity, track unresolved and overdue complaints, detect recurring issues, and recommend suitable actions or escalation.",
        "capabilities": [
            "What are the most serious student grievances that are still unresolved right now?",
            "Which grievances have been waiting the longest for resolution?",
            "Which department is receiving the highest number of complaints right now?",
            "Are there any complaints affecting a large number of students?",
            "Which grievances should be escalated immediately based on their severity and waiting time?",
            "Are there any recurring complaints that indicate a bigger institutional problem?",
            "How has the number of student grievances changed compared with previous months?",
            "Which departments are resolving complaints faster, and which have the longest delays?",
            "A new complaint has been submitted. Which department should handle it and how urgent is it?",
            "What actions should management take now to reduce recurring and overdue grievances?",
        ],
    },
    {
        "id": "PS-02",
        "round": "round-2",
        "domain": "examination",
        "domainLabel": "Examination Management",
        "title": "Examination Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages examination scheduling, student allocation, faculty duties, rooms, conflicts, and real-time examination operations.",
        "fullDescription": "Examination management involves changing information about students, courses, schedules, rooms, seating capacity, and faculty availability. The AI agent should identify timetable, room, seating, and invigilation conflicts, optimize room allocation, distribute invigilation duties, and respond to last-minute changes such as room unavailability or faculty absence.",
        "capabilities": [
            "Which examinations are scheduled today, and where are they being conducted?",
            "Are there any students who have conflicting or closely scheduled examinations?",
            "Which examination rooms are currently available, occupied, or unsuitable?",
            "Are any examination rooms over their seating capacity?",
            "How is the invigilation workload currently distributed among faculty?",
            "Are any invigilators unavailable or absent for their assigned duties?",
            "If a room becomes unavailable, which alternative room should be assigned?",
            "If an invigilator is absent, which available faculty member should replace them?",
            "Which examination sessions are likely to face seating or invigilation shortages?",
            "What changes should the examination team make now to improve examination operations?",
        ],
    },
    {
        "id": "PS-03",
        "round": "round-2",
        "domain": "disaster",
        "domainLabel": "Disaster Management",
        "title": "Disaster Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently monitors disasters, assesses risks, coordinates emergency resources, and supports evacuation and relief operations.",
        "fullDescription": "Disaster management involves changing information about weather, affected areas, roads, shelters, rescue teams, hospitals, and essential supplies. The AI agent should monitor current conditions, identify high-risk areas, recommend evacuation routes and shelters, and coordinate rescue teams, vehicles, food, water, and medicines.",
        "capabilities": [
            "Which areas are currently at the highest risk, and what is causing the risk?",
            "Which areas are already affected and require immediate assistance?",
            "Which roads or routes are currently blocked or unsafe for emergency vehicles?",
            "Which emergency shelters are open right now, and how much capacity is available?",
            "Which affected areas require immediate rescue or medical assistance?",
            "Are any areas running low on food, water, medicines, or other essential supplies?",
            "Which evacuation route should people in a high-risk area take right now?",
            "If the situation becomes worse, which areas are likely to be affected next?",
            "Where should additional rescue teams, vehicles, or supplies be deployed?",
            "What are the top three actions authorities should take right now?",
        ],
    },
    {
        "id": "PS-04",
        "round": "round-2",
        "domain": "public-education",
        "domainLabel": "Public Education Management",
        "title": "Public Education Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently monitors public education services, identifies learning and resource gaps, and recommends actions to improve educational outcomes.",
        "fullDescription": "Public education management involves changing information about students, attendance, academic performance, teachers, infrastructure, and learning resources. The AI agent should identify students and schools requiring support, detect teacher and resource shortages, analyze performance and attendance trends, and recommend interventions and resource allocation.",
        "capabilities": [
            "Which schools currently have the lowest attendance, and what could be causing the problem?",
            "Which schools or student groups are currently performing below the expected level?",
            "Which students are showing a recent decline in attendance or academic performance?",
            "Which schools currently have teacher shortages, and which subjects are most affected?",
            "Are any schools facing shortages of classrooms, textbooks, computers, or other resources?",
            "Which subjects are students struggling with the most across the region?",
            "How have attendance and academic performance changed compared with previous years?",
            "Which students or schools are likely to require additional support in the coming months?",
            "If additional teachers or resources are available, where should they be deployed first?",
            "What actions should education authorities take now to improve learning outcomes?",
        ],
    },
    {
        "id": "PS-05",
        "round": "round-2",
        "domain": "public-transport",
        "domainLabel": "Public Transport Management",
        "title": "Public Transport Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages public transportation services, passenger demand, routes, vehicles, delays, and real-time transport operations.",
        "fullDescription": "Public transportation involves changing information about buses, routes, passengers, vehicle capacity, traffic, delays, and breakdowns. The AI agent should monitor transport operations, identify overcrowded routes and disruptions, recommend alternatives, and redistribute vehicles based on passenger demand and current conditions.",
        "capabilities": [
            "Which buses are running right now, and which one should I take to reach my destination?",
            "Where is my bus right now, and when is it expected to reach my stop?",
            "How many seats are currently available on my bus, and is it likely to be overcrowded?",
            "Is my bus delayed or cancelled right now, and what is the reason?",
            "Is there any traffic, accident, roadblock, or route diversion affecting my journey?",
            "My regular bus is unavailable. Which alternative bus or route should I take?",
            "Which routes are overcrowded right now, and which nearby routes have spare capacity?",
            "Which buses are currently unavailable because of breakdowns or maintenance?",
            "Which routes are likely to become overcrowded during the next peak period?",
            "Based on current demand, capacity, traffic, and delays, how should buses be redistributed right now?",
        ],
    },
]

for problem in problem_statements:
    problem["techStack"] = ["Real-time data integration", "AI recommendations", "Analytics"]
    problem["sampleFlow"] = "Use the challenge questions to demonstrate a complete data-to-decision workflow."
    problem["rubricFocus"] = "Real-time information processing, intelligent reasoning, prioritization, recommendations, and actionable decision-making."
