problem_statements = [
    {
        "id": "PS-01",
        "round": "round-1",
        "domain": "hostel",
        "domainLabel": "Hostel Management",
        "title": "Hostel Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages hostel allocation, complaints, occupancy, and student accommodation services.",
        "fullDescription": "University hostel management involves continuously changing information about room availability, occupancy, student allocations, room changes, maintenance issues, complaints, and hostel facilities. Managing this information manually can result in delays, inefficient room utilization, unresolved complaints, and difficulty responding to sudden accommodation requirements. The AI agent should maintain an up-to-date understanding of hostel capacity and room availability. It should intelligently match students with suitable rooms while considering relevant constraints and preferences. The agent should monitor complaints and identify issues that require immediate attention. It should detect recurring problems across rooms, facilities, or hostel blocks. The system should prioritize complaints based on severity, waiting time, and impact on students. It should identify current and potential overcrowding situations. The agent should also recommend suitable actions when rooms or hostel facilities suddenly become unavailable. It should assist hostel administrators in making fair and efficient allocation decisions. The final system should demonstrate real-time monitoring, reasoning, prioritization, optimization, and actionable recommendations.",
        "capabilities": [
            "How much do I need to pay for my child's hostel and mess this semester, and are there any upcoming payments?",
            "Are rooms available right now, how many beds are vacant, and which hostel would be the best option for my child?",
            "How many students are currently staying in each hostel block, and what is the student-to-warden ratio?",
            "What hostel facilities are working right now, such as Wi-Fi, water, electricity, laundry, and study rooms?",
            "Who is the warden responsible for my child's hostel, and what support is available if there is a problem?",
            "How safe is the hostel right now? Are the CCTV cameras, security guards, and entry checks working properly?",
            "What are the hostel timings and leave rules, and what approval is needed if my child wants to go home this weekend?",
            "My child says the food quality has gone down. Can you check the latest student feedback and tell me whether this is a common problem?",
            "My child is having a problem with their room. Are better rooms available, and what action can be taken to resolve the issue?",
            "Are there any serious complaints, safety issues, or other problems in the hostel right now that require immediate attention, and how would parents be informed if their child is affected?",
        ],
    },
    {
        "id": "PS-02",
        "round": "round-1",
        "domain": "placements",
        "domainLabel": "Placements Management",
        "title": "Placements Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages and supports the university placement process.",
        "fullDescription": "University placement activities involve large and continuously changing amounts of information related to students, recruiters, job roles, eligibility criteria, skills, applications, interviews, offers, and placement outcomes. This information is often distributed across multiple systems, making it difficult for students and placement teams to obtain timely and meaningful insights. The AI agent should be able to understand student profiles and recruiter requirements and identify suitable opportunities in real time. It should evaluate eligibility and match students with relevant roles based on multiple factors rather than simple keyword matching. The agent should identify skill gaps and recommend suitable actions for improving employability. It should analyze placement trends and identify areas that require attention from the placement team. The system should be capable of responding to changing recruiter requirements and student circumstances. It should provide personalized recommendations instead of only displaying stored information. The agent should also support placement teams in prioritizing recruiters, students, and interventions. The final system should demonstrate intelligent reasoning, data integration, recommendations, and actionable decision-making.",
        "capabilities": [
            "Which companies are hiring right now, and which students are currently eligible for their jobs?",
            "How many students are currently placed, unplaced, and still waiting for placement opportunities in each department?",
            "What is our current placement percentage, and how does each department compare with the university average?",
            "Which companies are currently offering the most jobs and the highest salary packages?",
            "Which students are the best match for the jobs currently available, and why?",
            "What skills are companies currently looking for, and which important skills are missing among our students?",
            "Which departments are currently performing below the expected placement level, and what could be the reasons?",
            "Which students are currently at higher risk of remaining unplaced, and what should we do to improve their chances?",
            "How are our current placement results compared with the previous placement seasons?",
            "Which companies that recruited our students earlier should we approach again, and which new companies should we target?",
            "Which departments have the highest average salary package, and what factors are contributing to their performance?",
            "Are there any companies or job roles where many eligible students are not applying, and why might that be happening?",
            "Based on current recruiter demand and student performance, which departments or skills are likely to face placement challenges in the coming months?",
            "If we want to improve the placement percentage this year, which students, departments, skills, or recruiters should we prioritize first?",
            "As management, what are the top three actions we should take right now to improve placements based on current student data, recruiter demand, and placement trends?",
        ],
    },
    {
        "id": "PS-03",
        "round": "round-1",
        "domain": "transportation",
        "domainLabel": "Campus Transportation",
        "title": "Campus Transport Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Students and staff often face difficulties in knowing bus routes, timings, availability, delays, and changes in campus transportation schedules.",
        "fullDescription": "Develop an AI Campus Transport Agent that provides real-time or scheduled information about campus buses and transportation services. The agent can suggest the best route, provide estimated arrival times, notify users about delays, and help transport administrators analyze demand.",
        "capabilities": [
            "Which buses are running right now, and which one should I take to reach campus?",
            "Where is my bus right now, and when is it expected to reach my pickup point?",
            "How many seats are available on my bus right now, and is it likely to be overcrowded?",
            "Is my bus delayed or cancelled right now, and what is the reason?",
            "Is there any traffic, roadblock, or route diversion currently affecting my journey?",
            "My regular bus is unavailable. Which alternative bus can I take right now?",
            "How many students are currently waiting at each pickup stop?",
            "Which routes are overcrowded right now, and which nearby routes have spare capacity?",
            "Has my child's bus reached the pickup point, and is it running according to schedule?",
            "Is there any current safety issue, breakdown, or unexpected change affecting my child's bus?",
            "Which routes are experiencing the longest delays today, and what are the main reasons?",
            "Which buses are currently unavailable due to maintenance or other issues, and which routes are affected?",
            "Based on the number of students waiting and available seats, where is an additional bus needed right now?",
            "If a bus breaks down right now, which available bus can take its passengers with the least disruption?",
            "Based on current demand, bus capacity, delays, and route conditions, how should the buses be redistributed right now?",
        ],
    },
    {
        "id": "PS-04",
        "round": "round-1",
        "domain": "curriculum",
        "domainLabel": "Curriculum Management",
        "title": "Curriculum Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages and supports the university curriculum and academic course planning process.",
        "fullDescription": "University curriculum management involves large and continuously changing amounts of information related to courses, electives, prerequisites, credits, faculty, timetables, student enrollments, academic performance, and industry requirements. This information is often distributed across multiple systems, making it difficult for students and academic teams to make timely and informed decisions. The AI agent should understand curriculum structures, student academic profiles, course availability, and academic requirements in real time. It should identify suitable courses and electives for students while considering prerequisites, credits, timetable constraints, and career goals. The agent should identify academic and curriculum gaps and recommend suitable courses or learning pathways based on individual student needs. It should analyze course enrollment, student performance, and demand trends to identify subjects or areas that require attention. The system should be capable of responding to changing course availability, student requirements, and industry skill demands. It should provide personalized course recommendations instead of only displaying curriculum information. The agent should also support faculty, HODs, and academic management in making informed decisions about course planning, capacity, and curriculum improvements. The final system should demonstrate intelligent reasoning, data integration, personalized recommendations, trend analysis, and actionable academic decision-making.",
        "capabilities": [
            "Which subjects can I take this semester based on the courses I have already completed?",
            "Which electives are currently available, and which one would be better for my career goal?",
            "Do I have any prerequisite, credit, or timetable conflicts with the subjects I have selected?",
            "Which courses currently have the highest number of students, and are seats still available?",
            "Which subjects currently have high failure or repeat rates?",
            "What skills are companies currently looking for that are not well covered in our curriculum?",
            "How are students performing in my current subjects compared with previous batches?",
            "I want to become a data scientist/software developer/etc. Which subjects should I choose to build the right learning path?",
            "Which courses or subjects should be updated based on current student performance and industry requirements?",
            "If I want to complete my degree on time while preparing for my career goal, what course plan would you recommend?",
        ],
    },
    {
        "id": "PS-05",
        "round": "round-1",
        "domain": "admissions",
        "domainLabel": "Admissions Management",
        "title": "Admissions Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages and supports the university admission process from application to enrollment.",
        "fullDescription": "University admission activities involve large and continuously changing amounts of information related to applicants, programs, eligibility criteria, applications, documents, entrance scores, fees, seat availability, deadlines, and admission decisions. This information is often distributed across multiple systems, making it difficult for applicants and admission teams to obtain timely and meaningful insights. The AI agent should understand applicant profiles, program requirements, application status, and seat availability in real time. It should evaluate applicant eligibility and identify suitable programs based on academic qualifications, interests, and other relevant factors. The agent should identify incomplete applications, missing documents, upcoming deadlines, and pending actions that require immediate attention. It should analyze application trends and program demand to identify courses that are becoming highly competitive or approaching capacity. The system should be capable of responding to changing seat availability, applicant preferences, admission requirements, and application status. It should provide personalized program recommendations instead of only displaying admission information. The agent should also support admission teams in prioritizing applications, identifying potential bottlenecks, and improving the admission process. The final system should demonstrate intelligent reasoning, data integration, personalized recommendations, trend analysis, and actionable decision-making.",
        "capabilities": [
            "How many seats are currently available in the course I am interested in, and how many applications have been received?",
            "Am I currently eligible for this course based on my marks, entrance score, and other requirements?",
            "Is my application complete, or is anything still missing that I need to submit?",
            "What are the important admission deadlines coming up, and do I need to take any action now?",
            "If I am not eligible for my preferred course, which other courses would be a good option for me?",
            "Which courses are currently receiving the most applications, and which ones still have good availability?",
            "How does the current admission demand compare with the previous admission cycle?",
            "Based on the current applications and available seats, which courses are likely to fill up soon?",
            "I have completed my application but have not received an update. Can you check its current status and tell me what I should do next?",
            "If I want the best course for my marks, interests, and career goals, which available option would you recommend and why?",
        ],
    },
    {
        "id": "PS-06",
        "round": "round-1",
        "domain": "agriculture",
        "domainLabel": "Agriculture Management",
        "title": "Agriculture Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently supports farmers and agriculture stakeholders in making informed decisions about crops, resources, markets, and farm operations",
        "fullDescription": "Agriculture involves continuously changing information related to weather, soil conditions, crops, pests, diseases, irrigation, fertilizers, market prices, government schemes, and farm resources. Farmers often need to make decisions quickly while relying on information from multiple sources. The AI agent should understand farm conditions, crop requirements, weather patterns, and market information in real time. It should recommend suitable crops, irrigation schedules, fertilizers, and farming practices based on local conditions. The agent should identify possible crop diseases, pest risks, and weather-related threats and suggest appropriate preventive actions. It should analyze current market prices and help farmers identify suitable markets and selling opportunities. The system should also provide information about relevant government schemes, subsidies, and agricultural support services. It should help agricultural officers and organizations identify areas facing crop, weather, or resource-related risks. The final system should demonstrate real-time monitoring, reasoning, prediction, personalized recommendations, and actionable decision-making.",
        "capabilities": [
            "What crop would be best to grow right now based on my soil, weather, and local conditions?",
            "What is the current market price for my crop, and which nearby market is offering the best price?",
            "Is there any weather condition expected soon that could affect my crop, and what should I do?",
            "My crop is showing signs of disease. What could be the problem, and what action should I take?",
            "How much water and fertilizer does my crop need at its current growth stage?",
            "Are there any government schemes or subsidies I can currently apply for?",
            "Which crops are currently facing high demand, and could switching crops improve my expected income?",
            "Which areas are currently at higher risk of pest attacks, water shortages, or crop damage?",
            "Based on current weather, crop conditions, and market prices, what should farmers in this region prioritize right now?",
            "As an agriculture officer, which villages or farmers need immediate support based on current crop, weather, and resource conditions?",
        ],
    },
    {
        "id": "PS-07",
        "round": "round-1",
        "domain": "healthcare",
        "domainLabel": "Healthcare Management",
        "title": "Healthcare Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently supports patients, healthcare professionals, and hospital administrators in managing healthcare services and resources.",
        "fullDescription": "Healthcare services involve continuously changing information related to patients, doctors, appointments, beds, medicines, laboratory tests, medical resources, and hospital operations. Patients often face difficulty finding the right healthcare service at the right time, while hospitals need to efficiently manage their resources. The AI agent should provide real-time information about appointments, doctors, departments, beds, and available healthcare services. It should help patients identify suitable healthcare services based on their needs while respecting appropriate medical and privacy boundaries. The agent should assist doctors and staff by organizing relevant patient and operational information. It should monitor hospital capacity, waiting times, and resource availability to identify areas requiring attention. The system should detect operational bottlenecks and help prioritize cases based on urgency and available resources. It should analyze healthcare service trends and recommend improvements to hospital management. The final system should demonstrate real-time information processing, intelligent reasoning, prioritization, analytics, and actionable decision-making.",
        "capabilities": [
            "Which doctors are available right now, and when is the earliest appointment I can get?",
            "How long is the current waiting time in the emergency department or outpatient department?",
            "Which department should I visit for my current healthcare need?",
            "Are beds currently available, and which departments have the highest occupancy?",
            "Are any important medicines, equipment, or medical resources currently unavailable?",
            "Which departments are experiencing the highest patient load right now?",
            "Which patients or cases require immediate attention based on the available information?",
            "How has patient demand changed recently, and which departments are likely to become overcrowded?",
            "As a hospital administrator, where should staff or resources be moved right now to reduce waiting time?",
            "What are the biggest operational problems in the hospital currently, and what actions should management take first?",
        ],
    },
    {
        "id": "PS-08",
        "round": "round-1",
        "domain": "waste",
        "domainLabel": "Waste Management",
        "title": "Waste Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently manages waste collection, segregation, transportation, recycling, and disposal across communities.",
        "fullDescription": "Waste management involves continuously changing information related to waste generation, collection schedules, vehicles, collection points, recycling facilities, disposal sites, and citizen complaints. Inefficient collection and poor waste segregation can lead to overflowing bins, environmental problems, increased costs, and unhealthy living conditions. The AI agent should monitor waste levels, collection status, vehicle availability, and disposal capacity in real time. It should identify locations requiring immediate waste collection and intelligently prioritize collection routes. The system should optimize waste collection vehicles based on waste volume, distance, traffic, and available capacity. It should identify areas with poor waste segregation and recurring collection problems. The agent should analyze waste generation patterns and predict locations that are likely to require additional collection capacity. It should assist citizens in reporting and tracking waste-related issues. The system should support municipal authorities in improving recycling, reducing operational costs, and managing waste efficiently. The final system should demonstrate real-time monitoring, optimization, prediction, prioritization, and actionable decision-making.",
        "capabilities": [
            "Which waste collection points are full or overflowing right now?",
            "When will the waste from my area be collected, and is the collection vehicle currently on schedule?",
            "My area's waste has not been collected. What is the current status and when can I expect collection?",
            "Which areas currently have the highest amount of uncollected waste?",
            "Which collection vehicles are currently available, and which ones are full or under maintenance?",
            "Which areas are generating the most waste, and how does this compare with other areas?",
            "Are there locations where waste segregation is currently poor or causing repeated problems?",
            "Which waste collection routes are taking the most time, and what is causing the delays?",
            "Based on current waste levels and collection capacity, where should additional vehicles be sent right now?",
            "As a municipal officer, what three actions should we take immediately to improve waste collection and reduce overflowing waste?",
        ],
    },
    {
        "id": "PS-09",
        "round": "round-1",
        "domain": "employment",
        "domainLabel": "Employment Management",
        "title": "Employment Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently connects job seekers with suitable employment opportunities while supporting employers and employment agencies in efficient talent matching.",
        "fullDescription": "Employment services involve continuously changing information related to job vacancies, candidate profiles, skills, qualifications, salaries, locations, employer requirements, applications, and hiring status. Job seekers often struggle to identify suitable opportunities and understand which skills they need to improve. Employers also face difficulty finding candidates who match their requirements beyond simple keyword-based searches. The AI agent should understand candidate profiles and current job requirements in real time. It should intelligently match candidates with suitable jobs based on skills, experience, qualifications, location, salary expectations, and career goals. The agent should identify skill gaps and recommend relevant training or upskilling opportunities. It should track application progress and identify opportunities that require immediate action. The system should analyze employment trends and identify growing or declining job roles and skill requirements. It should help employers identify suitable candidates and understand talent availability in the market. The final system should demonstrate intelligent matching, personalization, trend analysis, prediction, recommendations, and actionable decision-making.",
        "capabilities": [
            "Which jobs are available right now that match my skills and experience?",
            "Which of my skills are currently most in demand, and what skills should I improve?",
            "Which available job would be the best fit for me based on salary, location, skills, and career goals?",
            "What is the current status of my job applications, and which ones need my attention?",
            "Which companies are currently hiring the most, and what roles are they looking for?",
            "Which jobs are currently difficult to fill because employers cannot find enough suitable candidates?",
            "How are current job opportunities and salaries changing compared with recent months?",
            "Which skills are likely to be in higher demand in the coming months?",
            "As an employer, which candidates are the strongest matches for my current vacancy and why?",
            "As an employment officer, which sectors, skills, or candidate groups should we focus on to improve employment opportunities?",
        ],
    },
    {
        "id": "PS-10",
        "round": "round-1",
        "domain": "tourism",
        "domainLabel": "Tourism Management",
        "title": "Tourism Management Agent",
        "difficulty": "Hard",
        "diffClass": "hard",
        "summary": "Build an AI agent that intelligently supports tourists, tourism businesses, and authorities in planning and managing travel experiences and tourism services.",
        "fullDescription": "Tourism involves continuously changing information related to destinations, attractions, weather, transportation, accommodation, events, crowd levels, prices, and visitor preferences. Tourists often need to make quick decisions based on current conditions, while tourism businesses and authorities need to manage changing visitor demand. The AI agent should provide real-time information about attractions, transportation, accommodation, events, weather, and local conditions. It should understand tourist preferences, budgets, available time, and interests to create personalized travel plans. The agent should recommend suitable destinations and activities based on current crowd levels, weather, opening status, and travel conditions. It should identify disruptions such as closures, traffic, weather problems, or overcrowding and suggest alternatives. The system should analyze visitor trends and help tourism businesses understand demand for their services. It should assist tourism authorities in managing crowds, resources, and visitor safety. The final system should demonstrate real-time monitoring, personalization, recommendation, prediction, optimization, and actionable decision-making.",
        "capabilities": [
            "Which tourist places are open right now, and which ones are less crowded?",
            "I have only one day. What places can I visit based on the current weather and travel time?",
            "What is the fastest way to reach this tourist destination right now?",
            "Are there any current traffic, weather, road, or attraction closures that could affect my trip?",
            "Which hotels or accommodations are currently available within my budget and preferred location?",
            "What events or special activities are happening today or this weekend?",
            "Which tourist attractions are currently experiencing the highest visitor crowd?",
            "Based on current visitor demand, which destinations are likely to become overcrowded soon?",
            "As a tourism business owner, when should I increase staff or services based on current visitor demand?",
            "As a tourism authority, where should additional transport, security, or visitor support be deployed right now?",
        ],
    },
]

for problem in problem_statements:
    problem["techStack"] = ["Real-time data integration", "AI recommendations", "Analytics"]
    problem["sampleFlow"] = "Use the challenge questions to demonstrate a complete data-to-decision workflow."
    problem["rubricFocus"] = "Real-time information processing, intelligent reasoning, prioritization, recommendations, and actionable decision-making."
